                       -----------------------------
                        - Noname UTEK text file  -
                       -----------------------------
                       (Here are some hints for me.)

predmal[1]:=text na 1. dverach
predmal[2]:=pirane neznicene
predmal[3]:=pustena hudba 2
predmal[4]:=zobrate stehno
predmal[5]:=1. krat otvaranie tazkeho suplika
predmal[6]:=zobrate korenie
predmal[7]:=vznikla vinokena
predmal[8]:=zobraty zhrdz kluc
predmal[9]:=zobrary srobovak
predmal[10]:=podarilo sa otvorit suplik
predmal[11]:=zobrata flasa
predmal[12]:=prisrobovanie rucky
predmal[13]:=zobraty kluc zo sekretara
predmal[14]:=zruseny vratnik
predmal[15]:=odomknuta skrina v izbe 2
predmal[16]:=kluc zobraty zo suplika

predm[1]:=pouzite papuce

predm[6]:=minca zobrata
predm[7]:=stehno zobrate
predm[8]:=papuce zobrate
predm[9]:=zobrate korenie
predm[10]:=zobraty zhrdz kluc
predm[11]:=zobrary srobovak
predm[12]:=kluc zobraty
predm[13]:=zobrata flasa
predm[14]:=zobratie rucky
predm[15]:=zobraty okena
predm[16]:=zobraty kluc zo sekretara
predm[17]:=rucka zobrata

kabinet 4- kabinet rozhadzany
        3- zamknuty
        2- tmavy
        1- normalny

///* :::: CAST 2 ::::  *\\\

predmal[1]:= odtrhnuty plagat
predmal[2]:= zobraty drotik
predmal[3]:= odomknute dvere 1
predmal[4]:= plagat vsunuty
predmal[5]:= klucik vysunuty
predmal[5]:= klucik zobraty
predmal[6]:= klucka pripevnena
predmal[7]:= klucik vysunuty zobraty
predmal[8]:= zobraty papier (toaletny)
predmal[9]:= odstrihnuta snurka
predmal[10]:= zobrata vyvrtka
predmal[11]:= zobrata klucka
predmal[12]:= zobrate noznice
predmal[13]:= odomknuta skrinka
predmal[14]:= zobraty noz
predmal[15]:= zobraty obrusok
predmal[16]:=1. krat drotik
predmal[17]:=2. krat drotik
predmal[18]:=zobrate haraburdy
predmal[19]:=na olejovane panty
predmal[20]:=zobrate peniaze
predmal[21]:=zobrata handra
predmal[22]:=zatelefonovane
predmal[23]:=handra vsunuta
predmal[24]:=hadica vsunuta
predmal[25]:=tecie voda
predmal[26]:=su uduseny - yes

///* :::: CAST 3 ::::  *\\\

predmal[1]:=stlacene tlacitko
predmal[2]:=spytala sa

                                                      Hoe - 1995
